module "linux_vmss" {
  source                       = "./modules/vmss"
  for_each                     = var.vmss_configs
  vmss_name                    = each.value.vmss_name
  agent_pool_name              = var.agent_pool_name
  rg_name                      = each.value.rg_name
  location                     = each.value.location
  vm_size                      = each.value.vm_size
  admin_username               = each.value.admin_username
  subnet_id                    = each.value.subnet_id
  nic_name                     = each.value.nic_name
  ip_config_name               = values(each.value.ip_configurations)[0].name
  use_marketplace              = lookup(each.value, "use_marketplace", true)
  publisher                    = lookup(each.value, "publisher", "RedHat")
  offer                        = lookup(each.value, "offer", "RHEL")
  sku                          = lookup(each.value, "sku", "8-lvm-gen2")
  image_version                = lookup(each.value, "image_version", "latest")
  zones                        = each.value.zones
  os_disk_caching              = each.value.os_disk_caching
  os_disk_storage_account_type = each.value.os_disk_storage_account_type
  os_disk_size_gb              = each.value.os_disk_size_gb
  key_vault_id                 = each.value.key_vault_id
  tenant_id                    = each.value.tenant_id
  initial_instance_count       = each.value.instance_count
  min_instance_count           = each.value.min_instance_count
  max_instance_count           = each.value.max_instance_count
  environment                  = each.value.environment
  azdo_org_url                 = var.azdo_org_url
  agent_pat_secret_name        = var.agent_pat_secret_name
  key_vault_name               = each.value.key_vault_name
  agent_version                = each.value.agent_version
  agent_user                   = each.value.agent_user
  terraform_version            = each.value.terraform_version
}
